// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimalsController from "./animals_controller.js"
application.register("animals", AnimalsController)

import ButtonController from "./button_controller.js"
application.register("button", ButtonController)

import FavoritesController from "./favorites_controller.js"
application.register("favorites", FavoritesController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller.js"
application.register("navbar", NavbarController)
